theme: Cats
stream: 
  #Set enabled to false if you dont want a streamlink to be posted at the end of a Build Off
  enabled: true
  link: "http://www.Twitch.tv/FlexoTV"
buildoff:
  joinable: false
  running: false
  after: false
  maxcontestants: 36
layout:
  #plotwidth is counted including the stone slab borders
  plotwidth: 32
  pathwidth: 4
  plotsperrow: 6
startblock:
  #These are the worldname and coordinates of the glowstone block of the first plot
  world: world
  x: 0
  y: 64
  z: 0
boardstartblock:
  #These are the worldname and coordinates of first sign of the big plot layout board
  world: world
  x: -6
  y: 65
  z: -8
themesignblock:
  #These are the worldname and coordinates of sign that displays the theme
  world: world
  x: -2
  y: 65
  z: -8
contestants: 