theme: Cats
streamlink: http://www.Twitch.tv/FlexoTV
buildoff:
  joinable: false
  running: false
  after: false
  maxcontestants: 64
layout:
  #plotwidth is counted including the stone slab borders
  plotwidth: 32
  pathwidth: 4
  plotsperrow: 8
startblock:
  #These are the worldname and coordinates of the glowstone block of the first plot
  world: Yavana2
  x: 1751
  y: 64
  z: 1504
boardstartblock:
  #These are the worldname and coordinates of first sign of the big plot layout board
  world: Yavana2
  x: 1655
  y: 70
  z: 1446
contestants: 